version: 1.0#{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
artifacts:
- path: OpenMC2-libs-vs150.zip
  name: OpenMC2-libs-vs150.zip
deploy:
- provider: GitHub
  auth_token:
    secure: US2B1AJBegrxUhjKUfbocWUqavl636DxnaUnl8a7/waGexpd5Dp/mN6JBZIS+6Ee
  artifact: OpenMC2-libs-vs150.zip
  on:
    appveyor_repo_tag: true